security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt
   
    providers:
        in_memory: { memory: ~ }
        in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email
                   
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            
        main:
            access_denied_handler: App\Security\AccessDeniedHandler

            anonymous: ~


            guard:
                authenticators:
                     - App\Security\LoginFormAuthenticator


            provider: in_database
           

            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: logout
                target: home


            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path: 
                    /
    

    access_control:
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/user, roles: ROLE_USER } 
          - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY } 


